version: "3.8"

networks:
  bank-network:
services:
  accounts:
    container_name: accounts-service
    image: nileshzarkar/accounts:1.0
    ports:
      - 8080:8080
    networks: 
      - bank-network
  loans:
    container_name: loans-service
    image: nileshzarkar/loans:1.0
    ports:
      - 8081:8081
    networks: 
      - bank-network
  cards:
    container_name: cards-service
    image: nileshzarkar/cards:1.0
    ports:
      - 8082:8082
    networks: 
      - bank-network        
