version: "3.8"

networks:
  bank-network:
services:
  configserver:
    container_name: config-service
    image: nileshzarkar/configserver:1.0
    ports:
      - 8071:8071
    networks: 
      - bank-network
  accounts:
    container_name: accounts-service
    image: nileshzarkar/accounts:1.0
    ports:
      - 8080:8080
    networks: 
      - bank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s  
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  loans:
    container_name: loans-service
    image: nileshzarkar/loans:1.0
    ports:
      - 8081:8081
    networks: 
      - bank-network
    depends_on:
      - configserver      
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s  
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/      
  cards:
    container_name: cards-service
    image: nileshzarkar/cards:1.0
    ports:
      - 8082:8082
    networks: 
      - bank-network
    depends_on:
      - configserver      
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s  
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/         
